---
- name: Configure and Deploy Explore Lanka App
  hosts: webserver
  become: yes # Run tasks with sudo (root) privileges

  vars:
    dockerhub_username: "theek237"
    # This is passed from Jenkins as an extra-var: -e gemini_api_key=...
    gemini_api_key: ""

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker Engine and CLI
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Install Docker Compose Plugin
      apt:
        name: docker-compose-plugin
        state: present

    - name: Copy docker-compose.yml to the server
      copy:
        src: ../../docker-compose.prod.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Copy nginx.conf to the server
      copy:
        src: nginx.conf
        dest: /home/ubuntu/nginx.conf 

    - name: Clean up unused Docker resources
      shell: docker system prune -af
      ignore_errors: yes

    - name: Run docker compose up
      shell: |
        export DOCKERHUB_USERNAME={{ dockerhub_username }}
        export JWT_SECRET=thisisjustarandomsecretfornow
        export GEMINI_API_KEY={{ gemini_api_key }}
        docker compose -f /home/ubuntu/docker-compose.yml pull
        docker compose -f /home/ubuntu/docker-compose.yml up -d
      args:
        chdir: /home/ubuntu/